name: deploy
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_PASSWORD  }}
          password: ${{ secrets.DOCKER_USERNAME }}
          repository: ${{ github.repository  }}
          tag_with_ref: true
          tag_whit_sha: true
          tags: ${{ github.sha  }}

