name: deploy
on:
  push:
    branches:
            # - "main"
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository  }}
          tag_with_ref: true
          tag_whit_sha: true
          tags: ${{ github.sh  }}

